### ISSUE TITLE
Partner Landing Page: Project thumbnails’ width leads to problems

### ISSUE THREAD

**Issue by rittermo** [liqd/a4-product#120] opened 2017-11-28 11:20 UTC
Project thumbnails with different aspect ratios lead to a lot of movement on the partner page. We need to crop and/or restrict image aspect ratios here.

<img width="816" alt="bildschirmfoto 2017-11-28 um 12 18 33" src="https://user-images.githubusercontent.com/15341015/33317119-8d0c9b68-d436-11e7-8850-11a86891edfa.png">

**Comment by xi** [comment] 2017-12-05 15:25
Fixed in https://github.com/liqd/a4-product/pull/149

**Closed by xi** 2017-12-05 15:25 UTC

**Comment by xi** [comment] 2017-12-06 09:53
Duplicate of #114
