### ISSUE TITLE
Edit comment: Make text area larger

### ISSUE THREAD

**Issue by rittermo** [liqd/a4-product#111] opened 2017-11-28 11:08 UTC
When editing comments the textarea should be at least 4 lines high.

<img width="914" alt="bildschirmfoto 2017-11-28 um 12 07 43" src="https://user-images.githubusercontent.com/15341015/33316639-e70be7e2-d434-11e7-95cc-bfa11d0d222f.png">

**Comment by kleingeist** [comment] 2017-11-30 15:57
closed as duplicate of #102

**Closed by kleingeist** 2017-11-30 15:58 UTC
