### ISSUE TITLE
No margin between footer and confirmation button

### ISSUE THREAD

**Issue by fuzzylogic2000** [liqd/a4-product#88] opened 2017-11-28 10:39 UTC
![screenshot from 2017-11-28 11-39-01](https://user-images.githubusercontent.com/8178179/33315378-d3f6c6bc-d430-11e7-95c0-0d6be86e5172.png)

**Comment by kleingeist** [comment] 2017-11-30 16:43
duplicate of #87

**Closed by kleingeist** 2017-11-30 16:43 UTC
Labels: styling
