### ISSUE TITLE
No map available in idea mapping process

### ISSUE THREAD

**Issue by rukala** [liqd/a4-product#61] opened 2017-11-08 09:46 UTC
When creting a new idea mapping process there is currently no map available from which to choose an area.

**Comment by rukala** [comment] 2017-11-08 09:47
![bildschirmfoto 2017-11-08 um 10 46 45](https://user-images.githubusercontent.com/11075214/32542218-27068b22-c472-11e7-9d63-55f9adad93b9.png)

**Comment by xi** [comment] 2017-11-08 16:34
Works for me locally. Maybe the bounding box is misconfigured on the test server?

**Comment by kleingeist** [comment] 2017-11-09 14:39
the errors occurs due to the missing js files in the meinberlin package. closed as this is a duplicate of #67

**Closed by kleingeist** 2017-11-09 14:39 UTC
Labels: bug
