### ISSUE TITLE
Biography text field should be bigger

### ISSUE THREAD

**Issue by MagdaN** [liqd/a4-product#93] opened 2017-11-28 10:46 UTC
![bildschirmfoto 2017-11-28 um 11 46 15](https://user-images.githubusercontent.com/2905743/33315728-d048fbec-d431-11e7-808c-cca22aaea622.png)

**Comment by kleingeist** [comment] 2017-11-30 15:57
closed as duplicate of #102

**Closed by kleingeist** 2017-11-30 15:57 UTC
