### ISSUE TITLE
#2322: margins and layout on mobile screens

### ISSUE THREAD

**Issue by rittermo** [liqd/a4-product#1084] opened 2019-10-21 09:03 UTC
The margins on left and right are not symmetrical and the gradient line breaks in the header and the footer. Also the padding inside the grey area is still rather large and takes up a lot of space on small screens. Can we make it as small as the outer white margin?

![IMG_0605](https://user-images.githubusercontent.com/15341015/67190797-eae3a980-f3f0-11e9-88ec-c6de53f35ab7.PNG)

We should switch the white space situation here, so that the content blocks are more discernible. There needs to as much white space after the elements when the three-column element switches to a one-column layout as there currently is after the image. And there should be less white space after the image (about as much as there currently is after the end of an column element.

![IMG_0606](https://user-images.githubusercontent.com/15341015/67191728-6eea6100-f3f2-11e9-9603-0cbe6f8963ac.PNG)

There should be half as much space between the „for…“ byline and the headline.
![IMG_0609](https://user-images.githubusercontent.com/15341015/67191838-a822d100-f3f2-11e9-9d8a-26d7183c14b4.PNG)

The padding around the content inside the participation area should be smaller. As small as the white space around the grey area on the landing page. 

![IMG_0613](https://user-images.githubusercontent.com/15341015/67191220-8ffe8200-f3f1-11e9-97f4-9f91e0037c85.PNG)

Images in the content area don’t resize correctly vertically
https://product-dev.liqd.net/buro-fur-vielfalt/projects/vision-2030/

![IMG_0616](https://user-images.githubusercontent.com/15341015/67192532-0b613300-f3f4-11e9-80c8-e9b09abcf2d3.jpg)

The tabs don’t fit into one line anymore on very small screens (320px width). For the 576px breakpoint, we should decrease the font-size to 1rem, the padding to .2em and increase the margin-right to -1px, to still make the feel separated enough to be clickable

![Bildschirmfoto 2019-10-21 um 11 24 37](https://user-images.githubusercontent.com/15341015/67193622-e241a200-f3f5-11e9-9bec-828f80dcaa81.png)

On all screens: The „angemeldet bleiben“ should not be indented and the Reset password link should be underneath the button with about a line-height of white-space. 
Mobile: The text-input should be full width on small screens. 

![Bildschirmfoto 2019-10-21 um 12 04 36](https://user-images.githubusercontent.com/15341015/67196394-05bb1b80-f3fb-11e9-932d-7de8466508c8.png)

**Comment by phillimorland** [comment] 2019-10-21 14:10
note: check after pm-2019-10-issue-fixes is merged with updated spacing

**Comment by phillimorland** [comment] 2019-10-21 15:16
@rittermo cannot reproduce issue with top ribbon, what browser did you find it on?

**Comment by fuzzylogic2000** [comment] 2019-10-21 15:42
I could reproduce it... On chrome and duckduckgo on android:
![Screenshot_20191021-173826](https://user-images.githubusercontent.com/8178179/67220429-1767e780-f42a-11e9-9327-51e131559dd9.png)
![Screenshot_20191021-173935](https://user-images.githubusercontent.com/8178179/67220431-1767e780-f42a-11e9-8d6f-c102127d4ffa.png)

**Comment by phillimorland** [comment] 2019-10-22 15:30
ref: Images in the content area don’t resize correctly vertically
https://product-dev.liqd.net/buro-fur-vielfalt/projects/vision-2030/
@rittermo when adding images via ck editor, you can choose the size of your image which then becomes a inline style and as a class name is not applied, it seems it can't be overwritten, hopefully this issue will be resolved with a new editor. Until then you can assign a size via the editor but it still wont be very responsive.

**Closed as completed** 2019-10-23 15:05 UTC
