### ISSUE TITLE
Description field should be bigger (create project)

### ISSUE THREAD

**Issue by MagdaN** [liqd/a4-product#106] opened 2017-11-28 11:03 UTC
![bildschirmfoto 2017-11-28 um 12 02 04](https://user-images.githubusercontent.com/2905743/33316387-174619ba-d434-11e7-8262-1ba06bfdca84.png)

**Comment by kleingeist** [comment] 2017-11-30 15:59
closed as duplicate of #102

**Closed by kleingeist** 2017-11-30 15:59 UTC
