### ISSUE TITLE
Uploading images in project description fails

### ISSUE THREAD

**Issue by rukala** [liqd/a4-product#60] opened 2017-11-08 09:43 UTC
Uploading images in project description through ck editor fails, images are not shown, but saved on server.

**Comment by xi** [comment] 2017-11-08 16:35
Works for me locally.

**Comment by kleingeist** [comment] 2017-11-09 14:31
the images are stored with the access permissions  `-rw------- (600)` and are thus not readable by the user the nginx server is running.
@2e2a you reported this behavior before. did you find out why the permissions were set that way? and how did you resolve the problem on meinBerlin liqd/meinberlin#581

**Comment by 2e2a** [comment] 2017-11-09 14:34
No, I could not reproduce it and it did not occur again.

**Comment by kleingeist** [comment] 2017-11-09 14:58
i fixed the uploaded images permission for now manually by running 
`find /home/django/django/media/uploads -type f -exec chmod 644 {} \+`
from within the container. but this issue is really weird.

**Comment by kleingeist** [comment] 2017-12-11 16:52
the problem resulted from the django file storages behaviour in regard to temporary files. 
if a file of a size less then 2.5mb was uploaded it is stored first in memory and finally, after validation, stored to the disk
for files greater then 2.5mb a concrete temporary file with the 600 perms is created for the uploaded data. this file is later renamed to the desired filename, but the perms are not adapted.
to explicitly set the perms to 644 the https://docs.djangoproject.com/en/2.0/ref/settings/#std:setting-FILE_UPLOAD_PERMISSIONS setting has to be set.
this issue is closed as the deployment has been extended set FILE_UPLOAD_PERMISSIONS = 0o644

**Closed by kleingeist** 2017-12-11 16:52 UTC
Labels: bug
