### ISSUE TITLE
Comment: Larger textarea for comments

### ISSUE THREAD

**Issue by rittermo** [liqd/a4-product#101] opened 2017-11-28 10:59 UTC
Since comments are often longer than one line, the textarea for comments should be at least 4 lines tall per default

<img width="950" alt="bildschirmfoto 2017-11-28 um 11 58 11" src="https://user-images.githubusercontent.com/15341015/33316241-92d08d3c-d433-11e7-884c-0ff641388caa.png">

https://product-dev.liqd.net/falkensee/text/paragraphs/4/

**Comment by kleingeist** [comment] 2017-11-30 15:57
closed as duplicate of #102

**Closed by kleingeist** 2017-11-30 15:57 UTC
