### ISSUE TITLE
change comment: no margin between post and cancel

### ISSUE THREAD

**Issue by fuzzylogic2000** [liqd/a4-product#128] opened 2017-11-28 11:30 UTC
![screenshot from 2017-11-28 12-29-42](https://user-images.githubusercontent.com/8178179/33317599-e66ad67e-d437-11e7-9243-8264eb71fad5.png)

**Comment by kleingeist** [comment] 2017-11-30 16:40
duplicate of #112

**Closed by kleingeist** 2017-11-30 16:40 UTC
